import "server-only";

import { utils, write } from "xlsx";

import { logActivity } from "@/features/activity/utils/activity-log";
import { getEmployeeWorkModeLabel } from "@/features/employees/constants/employee-work-mode.config";
import type {
  AttendanceReportDetailsResult,
  AttendanceReportExportFormat,
  AttendanceReportPageData,
} from "@/features/attendance-reports/types/attendance-report.types";

function escapeCsv(value: string | number | null) {
  if (value === null) {
    return "";
  }

  const stringValue = String(value);

  if (/[",\n]/.test(stringValue)) {
    return `"${stringValue.replaceAll('"', '""')}"`;
  }

  return stringValue;
}

function getFileBaseName(pageData: AttendanceReportPageData) {
  return `attendance-report-${pageData.range.startDate}-to-${pageData.range.endDate}`;
}

function buildSummaryRows(pageData: AttendanceReportPageData) {
  return [
    ["Company", pageData.company.name],
    ["Period", pageData.range.label],
    ["Generated By", pageData.generatedBy],
    ["Generated At", pageData.generatedAt],
    ["Attendance Mode", pageData.attendanceModeLabel],
    ["Total Employees", pageData.summary.totalEmployees],
    ["Present", pageData.summary.present],
    ["Absent", pageData.summary.absent],
    ["Late", pageData.summary.late],
    ["On Leave", pageData.summary.onLeave],
    ["Remote", pageData.summary.remote],
    ["Hybrid", pageData.summary.hybrid],
    ["Working Days", pageData.summary.workingDays],
    ["Average Working Hours", pageData.summary.averageWorkingHoursLabel],
  ];
}

function buildEmployeeTable(pageData: AttendanceReportPageData) {
  return pageData.rows.map((row) => ({
    "Employee ID": row.employeeCode,
    "Employee Name": row.employeeName,
    Role: row.roleName,
    "Work Mode": getEmployeeWorkModeLabel(row.workMode),
    Department: row.departmentName ?? "",
    "Present Days": row.presentDays,
    "Absent Days": row.absentDays,
    "Late Days": row.lateDays,
    "Leave Days": row.leaveDays,
    "Remote Days": row.remoteDays,
    Weekend: row.weekendDays,
    Holiday: row.holidayDays,
    "Total Working Hours": row.totalWorkingHoursLabel,
    "Average Check-in": row.averageCheckIn ?? "",
    "Average Check-out": row.averageCheckOut ?? "",
    "Attendance %": row.attendancePercentage,
  }));
}

function buildDailyDetailsRows(detailsByEmployeeId: Map<string, AttendanceReportDetailsResult>) {
  return Array.from(detailsByEmployeeId.values()).flatMap((detail) =>
    detail.dailyItems.map((item) => ({
      "Employee ID": detail.employeeCode,
      "Employee Name": detail.employeeName,
      Date: item.date,
      "Check-in": item.checkIn ?? "",
      "Check-out": item.checkOut ?? "",
      "Working Hours": item.workingHoursLabel,
      Status: item.status,
      "Work Mode": getEmployeeWorkModeLabel(item.workMode),
      "Attendance Type": item.attendanceType
        ? getEmployeeWorkModeLabel(item.attendanceType)
        : "",
      Late: item.lateMinutes,
      Office: item.office,
      "Check-in Address": item.checkInAddress ?? "",
      "Check-out Address": item.checkOutAddress ?? "",
      "Check-in Latitude": item.checkInLatitude ?? "",
      "Check-in Longitude": item.checkInLongitude ?? "",
      "Check-in GPS Accuracy": item.checkInAccuracyMeters ?? "",
      "Check-in Browser": item.checkInDeviceBrowser ?? "",
      "Check-in Platform": item.checkInDevicePlatform ?? "",
      "Check-out Latitude": item.checkOutLatitude ?? "",
      "Check-out Longitude": item.checkOutLongitude ?? "",
      "Check-out GPS Accuracy": item.checkOutAccuracyMeters ?? "",
      "Check-out Browser": item.checkOutDeviceBrowser ?? "",
      "Check-out Platform": item.checkOutDevicePlatform ?? "",
      Distance: item.distanceLabel,
    })),
  );
}

function escapePdfText(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

function buildPdfBuffer(pageData: AttendanceReportPageData, companyLogo: string | null) {
  const pageWidth = 842;
  const pageHeight = 595;
  const marginLeft = 32;
  const marginTop = 32;
  const rowHeight = 16;
  const headerY = pageHeight - marginTop;
  const columns = [
    { key: "employeeCode", label: "Employee ID", width: 62 },
    { key: "employeeName", label: "Employee Name", width: 132 },
    { key: "roleName", label: "Role", width: 78 },
    { key: "presentDays", label: "Present", width: 44 },
    { key: "absentDays", label: "Absent", width: 44 },
    { key: "lateDays", label: "Late", width: 36 },
    { key: "leaveDays", label: "Leave", width: 38 },
    { key: "remoteDays", label: "Remote", width: 45 },
    { key: "totalWorkingHoursLabel", label: "Hours", width: 62 },
    { key: "attendancePercentage", label: "Attendance %", width: 62 },
    { key: "averageCheckIn", label: "Avg In", width: 48 },
    { key: "averageCheckOut", label: "Avg Out", width: 48 },
  ] as const;
  const rowsPerPage = 24;
  const rowPages: typeof pageData.rows[] = [];

  for (let index = 0; index < pageData.rows.length; index += rowsPerPage) {
    rowPages.push(pageData.rows.slice(index, index + rowsPerPage));
  }

  if (rowPages.length === 0) {
    rowPages.push([]);
  }

  const pageStreams = rowPages.map((rows, pageIndex) => {
    const commands: string[] = [];
    const text = (x: number, y: number, value: string, size = 10) => {
      commands.push(`BT /F1 ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdfText(value)}) Tj ET`);
    };
    const line = (x1: number, y1: number, x2: number, y2: number) => {
      commands.push(`${x1} ${y1} m ${x2} ${y2} l S`);
    };

    text(marginLeft, headerY, pageData.company.name, 16);
    text(marginLeft, headerY - 20, "Monthly Attendance Report", 13);
    text(
      marginLeft,
      headerY - 36,
      `${pageData.range.label} • Generated by ${pageData.generatedBy} • ${pageData.generatedAt}`,
      9,
    );

    if (companyLogo) {
      text(pageWidth - 180, headerY - 10, "Company logo on file", 9);
    }

    if (pageIndex === 0) {
      const summaryRows = [
        `Total Employees: ${pageData.summary.totalEmployees}`,
        `Present: ${pageData.summary.present}`,
        `Absent: ${pageData.summary.absent}`,
        `Late: ${pageData.summary.late}`,
        `On Leave: ${pageData.summary.onLeave}`,
        `Remote: ${pageData.summary.remote}`,
        `Hybrid: ${pageData.summary.hybrid}`,
        `Working Days: ${pageData.summary.workingDays}`,
        `Average Working Hours: ${pageData.summary.averageWorkingHoursLabel}`,
      ];

      summaryRows.forEach((row, index) => {
        const column = index < 5 ? 0 : 1;
        const rowIndex = column === 0 ? index : index - 5;
        text(
          marginLeft + column * 260,
          headerY - 62 - rowIndex * 14,
          row,
          9,
        );
      });
    }

    const tableTop = pageIndex === 0 ? headerY - 150 : headerY - 58;
    let cursorX = marginLeft;

    columns.forEach((column) => {
      text(cursorX + 2, tableTop, column.label, 8);
      cursorX += column.width;
    });

    line(marginLeft, tableTop - 4, pageWidth - marginLeft, tableTop - 4);

    rows.forEach((row, rowIndex) => {
      const y = tableTop - 18 - rowIndex * rowHeight;
      let x = marginLeft;

      columns.forEach((column) => {
        const rawValue = row[column.key];
        const value =
          column.key === "attendancePercentage"
            ? `${rawValue}%`
            : rawValue === null || rawValue === undefined
              ? ""
              : String(rawValue);
        const clippedValue =
          value.length > 22 ? `${value.slice(0, 21)}…` : value;

        text(x + 2, y, clippedValue, 8);
        x += column.width;
      });
    });

    text(
      pageWidth - 100,
      18,
      `Page ${pageIndex + 1} of ${rowPages.length}`,
      9,
    );

    return commands.join("\n");
  });

  const objects: string[] = [];
  const addObject = (value: string) => {
    objects.push(value);
    return objects.length;
  };

  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds: number[] = [];
  const contentIds: number[] = [];
  const pagesId = objects.length + pageStreams.length * 2 + 1;
  const catalogId = pagesId + 1;

  pageStreams.forEach((stream) => {
    const contentId = addObject(
      `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`,
    );
    contentIds.push(contentId);
    const pageId = addObject(
      `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`,
    );
    pageIds.push(pageId);
  });

  addObject(
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`,
  );
  addObject(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];

  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer << /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}

export const AttendanceExportService = {
  buildCsv(
    pageData: AttendanceReportPageData,
    detailsByEmployeeId: Map<string, AttendanceReportDetailsResult>,
  ) {
    const lines: string[] = [];

    buildSummaryRows(pageData).forEach(([label, value]) => {
      lines.push(`${escapeCsv(label)},${escapeCsv(value)}`);
    });

    lines.push("");
    lines.push(
      [
        "Employee ID",
        "Employee Name",
        "Role",
        "Work Mode",
        "Department",
        "Present Days",
        "Absent Days",
        "Late Days",
        "Leave Days",
        "Remote Days",
        "Weekend",
        "Holiday",
        "Total Working Hours",
        "Average Check-in",
        "Average Check-out",
        "Attendance %",
      ].join(","),
    );

    buildEmployeeTable(pageData).forEach((row) => {
      lines.push(
        Object.values(row)
          .map((value) => escapeCsv(value))
          .join(","),
      );
    });

    lines.push("");
    lines.push("Daily Attendance Details");
    lines.push(
      [
        "Employee ID",
        "Employee Name",
        "Date",
        "Check-in",
        "Check-out",
        "Working Hours",
        "Status",
        "Work Mode",
        "Attendance Type",
        "Late",
        "Office",
        "Check-in Address",
        "Check-out Address",
        "Check-in Latitude",
        "Check-in Longitude",
        "Check-in GPS Accuracy",
        "Check-in Browser",
        "Check-in Platform",
        "Check-out Latitude",
        "Check-out Longitude",
        "Check-out GPS Accuracy",
        "Check-out Browser",
        "Check-out Platform",
        "Distance",
      ].join(","),
    );

    buildDailyDetailsRows(detailsByEmployeeId).forEach((row) => {
      lines.push(
        Object.values(row)
          .map((value) => escapeCsv(value))
          .join(","),
      );
    });

    return {
      fileName: `${getFileBaseName(pageData)}.csv`,
      contentType: "text/csv; charset=utf-8",
      buffer: Buffer.from(`\uFEFF${lines.join("\n")}`, "utf8"),
    };
  },

  buildWorkbook(
    pageData: AttendanceReportPageData,
    detailsByEmployeeId: Map<string, AttendanceReportDetailsResult>,
  ) {
    const workbook = utils.book_new();
    const summarySheet = utils.aoa_to_sheet([
      ["Monthly Attendance Report"],
      [],
      ...buildSummaryRows(pageData),
      [],
      Object.keys(buildEmployeeTable(pageData)[0] ?? {}),
      ...buildEmployeeTable(pageData).map((row) => Object.values(row)),
    ]);
    const detailRows = buildDailyDetailsRows(detailsByEmployeeId);
    const detailsSheet = utils.aoa_to_sheet([
      ["Daily Attendance Details"],
      [],
      Object.keys(detailRows[0] ?? {
        "Employee ID": "",
        "Employee Name": "",
        Date: "",
        "Check-in": "",
        "Check-out": "",
        "Working Hours": "",
        Status: "",
        "Work Mode": "",
        "Attendance Type": "",
        Late: "",
        Office: "",
        "Check-in Address": "",
        "Check-out Address": "",
        "Check-in Latitude": "",
        "Check-in Longitude": "",
        "Check-in GPS Accuracy": "",
        "Check-in Browser": "",
        "Check-in Platform": "",
        "Check-out Latitude": "",
        "Check-out Longitude": "",
        "Check-out GPS Accuracy": "",
        "Check-out Browser": "",
        "Check-out Platform": "",
        Distance: "",
      }),
      ...detailRows.map((row) => Object.values(row)),
    ]);

    summarySheet["!cols"] = [
      { wch: 18 },
      { wch: 28 },
      { wch: 18 },
      { wch: 18 },
      { wch: 14 },
      { wch: 14 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 18 },
      { wch: 16 },
      { wch: 16 },
      { wch: 14 },
    ];
    detailsSheet["!cols"] = [
      { wch: 16 },
      { wch: 24 },
      { wch: 14 },
      { wch: 12 },
      { wch: 12 },
      { wch: 16 },
      { wch: 12 },
      { wch: 10 },
      { wch: 24 },
      { wch: 12 },
    ];
    summarySheet["!freeze"] = { xSplit: 0, ySplit: 17 };

    const titleCell = summarySheet.A1;

    if (titleCell) {
      titleCell.s = {
        font: { bold: true, sz: 16 },
      };
    }

    const headerRowIndex = 18;
    const headerColumns = "ABCDEFGHIJKLMNO".split("");

    headerColumns.forEach((column) => {
      const address = `${column}${headerRowIndex}`;
      const cell = summarySheet[address];

      if (cell) {
        cell.s = {
          font: { bold: true },
        };
      }
    });

    utils.book_append_sheet(workbook, summarySheet, "Summary");
    utils.book_append_sheet(workbook, detailsSheet, "Daily Details");

    return {
      fileName: `${getFileBaseName(pageData)}.xlsx`,
      contentType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      buffer: Buffer.from(
        write(workbook, {
          type: "buffer",
          bookType: "xlsx",
        }),
      ),
    };
  },

  buildPdf(
    pageData: AttendanceReportPageData,
    companyLogo: string | null,
  ) {
    return {
      fileName: `${getFileBaseName(pageData)}.pdf`,
      contentType: "application/pdf",
      buffer: buildPdfBuffer(pageData, companyLogo),
    };
  },

  async logDownload(input: {
    pageData: AttendanceReportPageData;
    format: AttendanceReportExportFormat;
  }) {
    await logActivity({
      companyId: input.pageData.company.id,
      module: "attendance",
      action: "downloaded",
      entityType: "attendance_reports",
      description: "Monthly Attendance Report Downloaded",
      metadata: {
        format: input.format,
        generatedBy: input.pageData.generatedBy,
        generatedAt: input.pageData.generatedAt,
        month: input.pageData.range.month,
        year: input.pageData.range.year,
        startDate: input.pageData.range.startDate,
        endDate: input.pageData.range.endDate,
        filters: input.pageData.filters,
      },
    });
  },
};
